---
abstract: 'URL shortening algorithm.'
author:
  - 'Alessandro Ghedini <alexbio@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-URL-Shorten
requires:
  Digest::MD5: 0
resources:
  homepage: http://search.cpan.org/dist/Algorithm-URL-Shorten/
  repository: git://github.com/AlexBio/Algorithm-URL-Shorten.git
version: 0.03
